name: Backend CI (UrbanPets)

on:
    push:
        branches: [dev, main]
        paths:
            - "src/Api/**"
            - "Directory.Build.props"
            - "Directory.Packages.props"
    pull_request:
        branches: [dev, main]
        paths:
            - "src/Api/**"
            - "Directory.Build.props"
            - "Directory.Packages.props"

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout del código
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Permite que herramientas como GitVersion lean el historial completo si es necesario

            - name: Configurar el SDK de .NET 10
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "10.0.x" # Utiliza la última versión estable del SDK de .NET 10

            - name: Restaurar dependencias NuGet
              run: dotnet restore UrbanPets.slnx

            - name: Compilar Solución
              run: dotnet build UrbanPets.slnx --configuration Release --no-restore

            - name: Ejecutar Pruebas Unitarias con Cobertura
              run: dotnet test UrbanPets.slnx --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults

            - name: Generar Reporte de Cobertura de Código
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                filename: TestResults/**/coverage.cobertura.xml
                badge: true
                fail_below_min: false # Puedes cambiarlo a true e indicar un 80 en el futuro para romper el pipeline si baja la cobertura
                format: markdown
                output: both

            - name: Publicar Resumen de Cobertura en el Pipeline
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
